-- Désactiver les vérifications de clés étrangères
SET FOREIGN_KEY_CHECKS=0;

-- Ajouter les colonnes manquantes à la table candidates
ALTER TABLE candidates
ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS github_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS twitter_url VARCHAR(255) DEFAULT NULL;

-- Ajouter les colonnes manquantes à la table users
ALTER TABLE users
ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL;

-- Mettre à jour la structure de la table candidates
ALTER TABLE candidates
MODIFY COLUMN summary TEXT DEFAULT NULL,
MODIFY COLUMN skills TEXT DEFAULT NULL,
MODIFY COLUMN experience TEXT DEFAULT NULL,
MODIFY COLUMN education TEXT DEFAULT NULL,
MODIFY COLUMN cv_path VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN location VARCHAR(255) DEFAULT NULL;

-- Réactiver les vérifications de clés étrangères
SET FOREIGN_KEY_CHECKS=1; 